force-app/main/default/objects/Candidate_Technical_Answer__c/Candidate_Technical_Answer__c.object-meta.xml
<CustomObject>
    <label>Candidate - Technical Answer</label>
    <nameField>
        <displayFormat>CT - {00000}</displayFormat>
        <label>Candidate - Technical Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidate - Technical Answers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate_Technical_Answer__c/fields/CandidateId__c.field-meta.xml
<CustomField>
    <fullName>CandidateId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CandidateId</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Candidate - Technical Answers</relationshipLabel>
    <relationshipName>Candidate_Technical_Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Candidate_Technical_Answer__c/fields/Response__c.field-meta.xml
<CustomField>
    <fullName>Response__c</fullName>
    <label>Response</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Candidate_Technical_Answer__c/fields/Technical_Round_3_Question__c.field-meta.xml
<CustomField>
    <fullName>Technical_Round_3_Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Technical Round (3) Question</label>
    <referenceTo>Technical_Round_3_Question__c</referenceTo>
    <relationshipLabel>Candidate - Technical Answers</relationshipLabel>
    <relationshipName>Candidate_Technical_Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Attitude_and_Professionalism_Tr__c.field-meta.xml
<CustomField>
    <fullName>Attitude_and_Professionalism_Tr__c</fullName>
    <label>Attitude and Professionalism</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Coding_Round_Reviewer__c.field-meta.xml
<CustomField>
    <fullName>Coding_Round_Reviewer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Coding Round Reviewer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Coding_Round_Status__c.field-meta.xml
<CustomField>
    <fullName>Coding_Round_Status__c</fullName>
    <label>Coding Round Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Test_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Communication_Skills_Tr__c.field-meta.xml
<CustomField>
    <fullName>Communication_Skills_Tr__c</fullName>
    <label>Communication Skills</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Confidence_Level_Tr__c.field-meta.xml
<CustomField>
    <fullName>Confidence_Level_Tr__c</fullName>
    <label>Confidence Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Learning_Skills_Tr__c.field-meta.xml
<CustomField>
    <fullName>Learning_Skills_Tr__c</fullName>
    <label>Learning Skills</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Problem_Solving_Skills_Tr__c.field-meta.xml
<CustomField>
    <fullName>Problem_Solving_Skills_Tr__c</fullName>
    <label>Problem Solving Skills</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Tech_Round_Interviewer__c.field-meta.xml
<CustomField>
    <fullName>Tech_Round_Interviewer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User record who interviewed the candidate</description>
    <label>Tech Round Interviewer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Technical_Round_Marks__c.field-meta.xml
<CustomField>
    <fullName>Technical_Round_Marks__c</fullName>
    <label>Technical Round Marks</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Technical_Round_Status__c.field-meta.xml
<CustomField>
    <fullName>Technical_Round_Status__c</fullName>
    <label>Technical Round Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Interview_Status_Picklist</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Technical_Skills_Tr__c.field-meta.xml
<CustomField>
    <fullName>Technical_Skills_Tr__c</fullName>
    <label>Technical Skills</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/TR_Comments__c.field-meta.xml
<CustomField>
    <fullName>TR_Comments__c</fullName>
    <label>TR Comments</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/TR_Question_Comments__c.field-meta.xml
<CustomField>
    <fullName>TR_Question_Comments__c</fullName>
    <label>TR Question Comments</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Technical_Round_3_Question__c/Technical_Round_3_Question__c.object-meta.xml
<CustomObject>
    <label>Technical Round (3) Question</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Technical Round ( 3 ) Question  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Technical Round (3) Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Technical_Round_3_Question__c/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Language_Picklist</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Technical_Round_3_Question__c/fields/Question_Difficulty__c.field-meta.xml
<CustomField>
    <fullName>Question_Difficulty__c</fullName>
    <label>Question Difficulty</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Easy</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Hard</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Interview_Status_Picklist.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Selected</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <customValue>
        <fullName>On Hold</fullName>
    </customValue>
    <masterLabel>Interview Status Picklist</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Language_Picklist.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>C</fullName>
    </customValue>
    <customValue>
        <fullName>DBMS</fullName>
    </customValue>
    <customValue>
        <fullName>HTML</fullName>
    </customValue>
    <customValue>
        <fullName>Java</fullName>
    </customValue>
    <customValue>
        <fullName>JavaScript</fullName>
    </customValue>
    <customValue>
        <fullName>Python</fullName>
    </customValue>
    <customValue>
        <fullName>SQL</fullName>
    </customValue>
    <customValue>
        <fullName>Logical</fullName>
    </customValue>
    <masterLabel>Language Picklist</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Test_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Not Started</fullName>
    </customValue>
    <customValue>
        <fullName>In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Selected</fullName>
    </customValue>
    <customValue>
        <fullName>On Hold</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <masterLabel>Test Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TechnicalRound3Controller.cls
/*
Description         :   To store the candidate data from TechnicalRound Tab
Test class name     :   TechnicalRound3ControllerTest
LWC                 :   ep_TechnicalRound3
*/

public without sharing class TechnicalRound3Controller {   
    
    // 
    @AuraEnabled
    public static String insertCTRecords(List<Map<String,String>> candidateQuestionInfo, String review, String candidateId, 
                                         List<Map<String,String>> ratings, String technicalRoundStatus) 
    {
        Integer technicalRoundMarks = 0;
        List<Candidate_Technical_Answer__c> CTrecords = new List<Candidate_Technical_Answer__c>();   
        
        for (Map<String,String> eachrecord : candidateQuestionInfo) {
            Candidate_Technical_Answer__c CTrecord = new Candidate_Technical_Answer__c();
            CTrecord.CandidateId__c = eachrecord.get('CandidateId');
            CTrecord.Technical_Round_3_Question__c = eachrecord.get('Id');
            CTrecord.Response__c = eachrecord.get('Response');            
            CTrecords.add(CTrecord);
        }
        
        Contact candidateRecord = [SELECT Id, TR_Comments__c, Technical_Round_Status__c, Technical_Round_Marks__c, Communication_Skills_Tr__c, 
                                   Problem_Solving_Skills_Tr__c, Technical_Skills_Tr__c, Learning_Skills_Tr__c, Confidence_Level_Tr__c, 
                                   Attitude_and_Professionalism_Tr__c 
                                   FROM Contact 
                                   WHERE Id =: candidateId LIMIT 1];
        candidateRecord.TR_Comments__c = review;
        candidateRecord.Technical_Round_Status__c = technicalRoundStatus;
            for (Map<String, String> ratingInfo : ratings) {
                if(ratingInfo.get('value') != null){
                    String fieldApiName = ratingInfo.get('apiName');
                    String fieldValue = ratingInfo.get('value');
                    technicalRoundMarks += Integer.valueOf(fieldValue); 
                    // Use dynamic field assignment
                    candidateRecord.put(fieldApiName, fieldValue);
                }
            }
        candidateRecord.Technical_Round_Marks__c = (Decimal.valueOf(technicalRoundMarks) / Decimal.valueOf(6)).setScale(2);
        
        try {
            insert CTrecords;
            update candidateRecord;
            
            return 'success';
        } catch (Exception e) {
            return e.getMessage();
        }
    }   
    
    // 
    @AuraEnabled
    public static Map<String, List<Technical_Round_3_Question__c>> getTechnicalQuestions(List<Map<String, String>> language) {
        Map<String, List<Technical_Round_3_Question__c>> labelQuestionMap = new Map<String, List<Technical_Round_3_Question__c>>();                
        Set<String> languageSet = new Set<String>();
        
        for (Map<String, String> eachlanguage : language) {
            languageSet.add(eachlanguage.get('label'));
        }
        
        List<Technical_Round_3_Question__c> questions = [SELECT Id, Question__c, Language__c, Question_Difficulty__c 
                                                         FROM Technical_Round_3_Question__c 
                                                         WHERE Language__c IN :languageSet];
        
        Map<String, List<Technical_Round_3_Question__c>> languageWithQuestions = new Map<String, List<Technical_Round_3_Question__c>>();
        for (Technical_Round_3_Question__c question : questions) {
            if (!languageWithQuestions.containsKey(question.Language__c)) {
                languageWithQuestions.put(question.Language__c, new List<Technical_Round_3_Question__c>());
            }
            languageWithQuestions.get(question.Language__c).add(question);
        }
        
        for (String category : languageSet) {
            List<Technical_Round_3_Question__c> allQuestionsForLanguage = languageWithQuestions.get(category);
            if (allQuestionsForLanguage != null) {
                labelQuestionMap.put(category, generateRandomQuestions(allQuestionsForLanguage));
            } else {
                labelQuestionMap.put(category, new List<Technical_Round_3_Question__c>());
            }
        }
        
        return labelQuestionMap;
    }
    
    // 
    public static List<Technical_Round_3_Question__c> generateRandomQuestions(List<Technical_Round_3_Question__c> inputList) {
        List<Technical_Round_3_Question__c> easyQuestions = new List<Technical_Round_3_Question__c>();
        List<Technical_Round_3_Question__c> mediumQuestions = new List<Technical_Round_3_Question__c>();
        List<Technical_Round_3_Question__c> hardQuestions = new List<Technical_Round_3_Question__c>();
        
        // Separate questions by difficulty
        for (Technical_Round_3_Question__c question : inputList) {
            if (question.Question_Difficulty__c == 'Easy') {
                easyQuestions.add(question);
            } else if (question.Question_Difficulty__c == 'Medium') {
                mediumQuestions.add(question);
            } else if (question.Question_Difficulty__c == 'Hard') {
                hardQuestions.add(question);
            }
        }
        
        // Randomly select 5 questions from each difficulty list
        List<Technical_Round_3_Question__c> randomQuestions = new List<Technical_Round_3_Question__c>();
        randomQuestions.addAll(selectRandomQuestions(easyQuestions, 5));
        randomQuestions.addAll(selectRandomQuestions(mediumQuestions, 5));
        randomQuestions.addAll(selectRandomQuestions(hardQuestions, 5));
        
        return randomQuestions;
    }
    
    // 
    private static List<Technical_Round_3_Question__c> selectRandomQuestions(List<Technical_Round_3_Question__c> questions, Integer num) {
        List<Technical_Round_3_Question__c> randomQuestions = new List<Technical_Round_3_Question__c>();        
        if (questions.size() <= num) {
            return questions;
        }
        
        while (randomQuestions.size() < num) {
            Integer randomIndex = Math.mod(Math.abs(Crypto.getRandomInteger()), questions.size());    
            randomQuestions.add(questions.remove(randomIndex));
        }
        
        return randomQuestions;
    }
    
    // 
    @AuraEnabled
    public static List<ExamPortalHelper.technicalReviewWrapper> getTechnicalAnswerData(String candidateId) {        
        List<ExamPortalHelper.technicalReviewWrapper> technicalAnswers = new List<ExamPortalHelper.technicalReviewWrapper> ();
        
        List<Candidate_Technical_Answer__c> CTrecords = [SELECT Id, CandidateId__c,
                                                         Response__c, Technical_Round_3_Question__c, 
                                                         Technical_Round_3_Question__r.Language__c, Technical_Round_3_Question__r.Question__c, 
                                                         Technical_Round_3_Question__r.Question_Difficulty__c 
                                                         FROM Candidate_Technical_Answer__c 
                                                         WHERE CandidateId__c = :candidateId];
        for (Candidate_Technical_Answer__c eachAnswrer : CTrecords) {
            ExamPortalHelper.technicalReviewWrapper technicalAnswer = new ExamPortalHelper.technicalReviewWrapper ();
            technicalAnswer.id = eachAnswrer.Id ;
            technicalAnswer.candidateId = eachAnswrer.CandidateId__c ;
            technicalAnswer.response = eachAnswrer.Response__c ;
            technicalAnswer.technicalQuestion = eachAnswrer.Technical_Round_3_Question__r.Question__c ;
            technicalAnswer.technicalLanguage = eachAnswrer.Technical_Round_3_Question__r.Language__c ;
            technicalAnswer.difficultyLevel = eachAnswrer.Technical_Round_3_Question__r.Question_Difficulty__c ;
            technicalAnswers.add(technicalAnswer);
        }
        
        return technicalAnswers;
    }
    
    // 
    @AuraEnabled
    public static Contact getCandidateData(String candidateId){
        Contact contact = [SELECT Id, Coding_Round_Status__c,Technical_Round_Status__c, Communication_Skills_Tr__c, TR_Question_Comments__c, 
                           TR_Comments__c, Problem_Solving_Skills_Tr__c, Technical_Skills_Tr__c, Learning_Skills_Tr__c, Confidence_Level_Tr__c, 
                           Attitude_and_Professionalism_Tr__c ,Technical_Round_Marks__c, Tech_Round_Interviewer__c,Tech_Round_Interviewer__r.Name,
                           Coding_Round_Reviewer__c
                           FROM Contact 
                           WHERE Id = :candidateId LIMIT 1];
        
        return contact;
    }
    
}