force-app/main/default/objects/Candidate_Technical_Answer__c/Candidate_Technical_Answer__c.object-meta.xml
<CustomObject>
    <label>Candidate - Technical Answer</label>
    <nameField>
        <displayFormat>CT - {00000}</displayFormat>
        <label>Candidate - Technical Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidate - Technical Answers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate_Technical_Answer__c/fields/CandidateId__c.field-meta.xml
<CustomField>
    <fullName>CandidateId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CandidateId</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Candidate - Technical Answers</relationshipLabel>
    <relationshipName>Candidate_Technical_Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Candidate_Technical_Answer__c/fields/Response__c.field-meta.xml
<CustomField>
    <fullName>Response__c</fullName>
    <label>Response</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Candidate_Technical_Answer__c/fields/Technical_Round_3_Question__c.field-meta.xml
<CustomField>
    <fullName>Technical_Round_3_Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Technical Round (3) Question</label>
    <referenceTo>Technical_Round_3_Question__c</referenceTo>
    <relationshipLabel>Candidate - Technical Answers</relationshipLabel>
    <relationshipName>Candidate_Technical_Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Attitude_and_Professionalism_Tr__c.field-meta.xml
<CustomField>
    <fullName>Attitude_and_Professionalism_Tr__c</fullName>
    <label>Attitude and Professionalism</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Communication_Skills_Tr__c.field-meta.xml
<CustomField>
    <fullName>Communication_Skills_Tr__c</fullName>
    <label>Communication Skills</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Confidence_Level_Tr__c.field-meta.xml
<CustomField>
    <fullName>Confidence_Level_Tr__c</fullName>
    <label>Confidence Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Exam_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Exam_Start_Date__c</fullName>
    <label>Exam Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Learning_Skills_Tr__c.field-meta.xml
<CustomField>
    <fullName>Learning_Skills_Tr__c</fullName>
    <label>Learning Skills</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Problem_Solving_Skills_Tr__c.field-meta.xml
<CustomField>
    <fullName>Problem_Solving_Skills_Tr__c</fullName>
    <label>Problem Solving Skills</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Technical_Round_Marks__c.field-meta.xml
<CustomField>
    <fullName>Technical_Round_Marks__c</fullName>
    <label>Technical Round Marks</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Technical_Round_Status__c.field-meta.xml
<CustomField>
    <fullName>Technical_Round_Status__c</fullName>
    <label>Technical Round Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Interview_Status_Picklist</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Technical_Skills_Tr__c.field-meta.xml
<CustomField>
    <fullName>Technical_Skills_Tr__c</fullName>
    <label>Technical Skills</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/TR_Comments__c.field-meta.xml
<CustomField>
    <fullName>TR_Comments__c</fullName>
    <label>TR Comments</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Technical_Round_3_Question__c/Technical_Round_3_Question__c.object-meta.xml
<CustomObject>
    <label>Technical Round (3) Question</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Technical Round ( 3 ) Question  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Technical Round (3) Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Technical_Round_3_Question__c/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Language_Picklist</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Technical_Round_3_Question__c/fields/Question_Difficulty__c.field-meta.xml
<CustomField>
    <fullName>Question_Difficulty__c</fullName>
    <label>Question Difficulty</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Easy</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Hard</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Interview_Status_Picklist.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Selected</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <customValue>
        <fullName>On Hold</fullName>
    </customValue>
    <masterLabel>Interview Status Picklist</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Language_Picklist.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>C</fullName>
    </customValue>
    <customValue>
        <fullName>DBMS</fullName>
    </customValue>
    <customValue>
        <fullName>HTML</fullName>
    </customValue>
    <customValue>
        <fullName>Java</fullName>
    </customValue>
    <customValue>
        <fullName>JavaScript</fullName>
    </customValue>
    <customValue>
        <fullName>Python</fullName>
    </customValue>
    <customValue>
        <fullName>SQL</fullName>
    </customValue>
    <customValue>
        <fullName>Logical</fullName>
    </customValue>
    <masterLabel>Language Picklist</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TechnicalRound3ControllerTest.cls
/*
Apex class		:	TechnicalRound3Controller
*/

@istest
public class TechnicalRound3ControllerTest {
    
    @istest
    static void testLabelValues() {
        Contact candidate = new contact(LastName = 'test', Exam_Start_Date__c = system.Today(),
                                       TR_Comments__c = '', Technical_Round_Status__c = '', Technical_Round_Marks__c = null, 
                                       Communication_Skills_Tr__c = null, Problem_Solving_Skills_Tr__c = null, Technical_Skills_Tr__c = null, 
                                       Learning_Skills_Tr__c = null, Confidence_Level_Tr__c =null, Attitude_and_Professionalism_Tr__c = null);
        insert candidate;
        
        List<Map<String, String>> languages = new List<Map<String, String>>();
        languages.add(new Map<String, String> { 'label' => 'Java', 'value' => 'Java' });
        languages.add(new Map<String, String> { 'label' => 'C', 'value' => 'C' });
        languages.add(new Map<String, String> { 'label' => 'DBMS', 'value' => 'DBMS' });
        languages.add(new Map<String, String> { 'label' => 'SQL', 'value' => 'SQL' });
        languages.add(new Map<String, String> { 'label' => 'HTML', 'value' => 'HTML' });
        languages.add(new Map<String, String> { 'label' => 'Python', 'value' => 'Python' });
        languages.add(new Map<String, String> { 'label' => 'JavaScript', 'value' => 'JavaScript' });
        
        List<Technical_Round_3_Question__c> technicalQuestions = new List<Technical_Round_3_Question__c>();
        technicalQuestions.add(new Technical_Round_3_Question__c(Question__c = 'What is Java1?', Language__c = 'Java', Question_Difficulty__c = 'Hard'));
        technicalQuestions.add(new Technical_Round_3_Question__c(Question__c = 'What is Java2?', Language__c = 'Java', Question_Difficulty__c = 'Hard'));
        technicalQuestions.add(new Technical_Round_3_Question__c(Question__c = 'What is Java3?', Language__c = 'Java', Question_Difficulty__c = 'Hard'));
        technicalQuestions.add(new Technical_Round_3_Question__c(Question__c = 'What is Java4?', Language__c = 'Java', Question_Difficulty__c = 'Hard'));
        technicalQuestions.add(new Technical_Round_3_Question__c(Question__c = 'What is Java5?', Language__c = 'Java', Question_Difficulty__c = 'Hard'));
        technicalQuestions.add(new Technical_Round_3_Question__c(Question__c = 'What is Java6?', Language__c = 'Java', Question_Difficulty__c = 'Hard'));
        technicalQuestions.add(new Technical_Round_3_Question__c(Question__c = 'What is C?', Language__c = 'C', Question_Difficulty__c = 'Medium'));
        technicalQuestions.add(new Technical_Round_3_Question__c(Question__c = 'What is DBMS?', Language__c = 'DBMS', Question_Difficulty__c = 'Easy'));
        technicalQuestions.add(new Technical_Round_3_Question__c(Question__c = 'What is SQL?', Language__c = 'SQL', Question_Difficulty__c = 'Hard'));
        technicalQuestions.add(new Technical_Round_3_Question__c(Question__c = 'What is HTML?', Language__c = 'HTML', Question_Difficulty__c = 'Medium'));
        technicalQuestions.add(new Technical_Round_3_Question__c(Question__c = 'What is Python?', Language__c = 'Python', Question_Difficulty__c = 'Easy'));
        technicalQuestions.add(new Technical_Round_3_Question__c(Question__c = 'What is JavaScript?', Language__c = 'JavaScript', Question_Difficulty__c = 'Hard'));
        
        insert technicalQuestions;
        
        List<Candidate_Technical_Answer__c> technicalAnswers = new List<Candidate_Technical_Answer__c>();
        technicalAnswers.add(new Candidate_Technical_Answer__c(CandidateId__c = candidate.Id, Response__c = '', Technical_Round_3_Question__c = technicalQuestions[0].Id)); 
        technicalAnswers.add(new Candidate_Technical_Answer__c(CandidateId__c = candidate.Id, Response__c = '', Technical_Round_3_Question__c = technicalQuestions[1].Id));
        technicalAnswers.add(new Candidate_Technical_Answer__c(CandidateId__c = candidate.Id, Response__c = '', Technical_Round_3_Question__c = technicalQuestions[2].Id));
        technicalAnswers.add(new Candidate_Technical_Answer__c(CandidateId__c = candidate.Id, Response__c = '', Technical_Round_3_Question__c = technicalQuestions[3].Id));
        technicalAnswers.add(new Candidate_Technical_Answer__c(CandidateId__c = candidate.Id, Response__c = '', Technical_Round_3_Question__c = technicalQuestions[4].Id));
        technicalAnswers.add(new Candidate_Technical_Answer__c(CandidateId__c = candidate.Id, Response__c = '', Technical_Round_3_Question__c = technicalQuestions[5].Id));
        technicalAnswers.add(new Candidate_Technical_Answer__c(CandidateId__c = candidate.Id, Response__c = '', Technical_Round_3_Question__c = technicalQuestions[6].Id));
        
        insert technicalAnswers;
        
        List<Map<String, String>> ratings = new List<Map<String,String>>();
        ratings.add(new Map<String, String> {'label'=>'Confidence Level','apiName'=>'Confidence_Level_Tr__c','value'=>'1'});
        ratings.add(new Map<String, String> {'label'=>'Attitude and Professionalism','apiName'=>'Attitude_and_Professionalism_Tr__c','value'=>'3'});
		ratings.add(new Map<String, String> {'label'=>'Learning Skills','apiName'=>'Learning_Skills_Tr__c','value'=>'2'});
		ratings.add(new Map<String, String> {'label'=>'Communication Skills','apiName'=>'Communication_Skills_Tr__c','value'=>'4'});
		ratings.add(new Map<String, String> {'label'=>'Problem Solving Skills','apiName'=>'Problem_Solving_Skills_Tr__c','value'=>'3'});
        ratings.add(new Map<String, String> {'label'=>'Technical Skills','apiName'=>'Technical_Skills_Tr__c','value'=>'5'});
        
        List<Map<String,String>> candidateQuestionInfo = new List<Map<String,String>>();
        candidateQuestionInfo.add(new Map<String, String> {'Id'=> technicalQuestions[0].Id,'Response'=>'Yes','CandidateId'=> candidate.Id});
        candidateQuestionInfo.add(new Map<String, String> {'Id'=> technicalQuestions[1].Id,'Response'=>'No','CandidateId'=> candidate.Id});
        candidateQuestionInfo.add(new Map<String, String> {'Id'=> technicalQuestions[2].Id,'Response'=>'Yes','CandidateId'=> candidate.Id});
        candidateQuestionInfo.add(new Map<String, String> {'Id'=> technicalQuestions[3].Id,'Response'=>'No','CandidateId'=> candidate.Id});
        
        TechnicalRound3Controller.getTechnicalQuestions(languages);
        TechnicalRound3Controller.getTechnicalAnswerData(candidate.Id);
        TechnicalRound3Controller.getCandidateData(candidate.Id);
        TechnicalRound3Controller.insertCTRecords(candidateQuestionInfo, 'Overall Technical Review', candidate.Id, ratings, 'Selected'); 
    }
}