force-app/main/default/objects/Candidate_Coding_Answer__c/Candidate_Coding_Answer__c.object-meta.xml
<CustomObject>
    <label>Candidate - Coding Answer</label>
    <nameField>
        <displayFormat>CA - {00000}</displayFormat>
        <label>Candidate - Coding Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidate - Coding Answers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate_Coding_Answer__c/fields/CandidateId__c.field-meta.xml
<CustomField>
    <fullName>CandidateId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CandidateId</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Candidate - Coding Answers</relationshipLabel>
    <relationshipName>Candidate_Coding_Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Candidate_Written_Answer__c/Candidate_Written_Answer__c.object-meta.xml
<CustomObject>
    <label>Candidate - Written Answer</label>
    <nameField>
        <displayFormat>CW-{00000}</displayFormat>
        <label>Candidate - Written Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidate - Written Answers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate_Written_Answer__c/fields/CandidateId__c.field-meta.xml
<CustomField>
    <fullName>CandidateId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CandidateId</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Candidate - Written Answers</relationshipLabel>
    <relationshipName>Candidate_Written_Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Coding_Round_Status__c.field-meta.xml
<CustomField>
    <fullName>Coding_Round_Status__c</fullName>
    <label>Coding Round Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Test_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Exam_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Exam_Start_Date__c</fullName>
    <label>Exam Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Sec_Consumed__c.field-meta.xml
<CustomField>
    <fullName>Sec_Consumed__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Consumed Seconds</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <label>Username</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Written_Test_Status__c.field-meta.xml
<CustomField>
    <fullName>Written_Test_Status__c</fullName>
    <label>Written Test Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Test_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Hall_Ticket_No__c.field-meta.xml
<CustomField>
    <fullName>Hall_Ticket_No__c</fullName>
    <label>Graduation Hallticket Number</label>
    <length>12</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Lead/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <label>Username</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Online_Exam_Settings__c/Online_Exam_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>EP_ExamPortal</label>
</CustomObject>

force-app/main/default/objects/Online_Exam_Settings__c/fields/Secret_Key__c.field-meta.xml
<CustomField>
    <fullName>Secret_Key__c</fullName>
    <label>Secret Key</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Test_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Not Started</fullName>
    </customValue>
    <customValue>
        <fullName>In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Selected</fullName>
    </customValue>
    <customValue>
        <fullName>On Hold</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <masterLabel>Test Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CandidateLoginHelper.cls
/*
Description			:	To check login data matches or not and generate questions for Written and coding Round
Test class name		:	CandidateLoginHelperTest
LWC					:	ep_LoginPage
*/

public without sharing class CandidateLoginHelper {
    
    //Lead to Contact Conversion
    @AuraEnabled
    public static String login(String htNumber) {
        
        List<Contact> contactList = [SELECT Id 
                                     FROM Contact 
                                     WHERE Username__c = :htNumber.toUpperCase()];
        System.debug('contactList::'+contactList);
        Account parentAccount = [SELECT Id 
                                 FROM Account 
                                 WHERE Name = :System.Label.Default_Account_Name];
        
        if (contactList.size() == 0) {
            String candidateId = '';
            List<Lead> leadList = [SELECT Id 
                                   FROM Lead 
                                   WHERE Username__c = :htNumber.toUpperCase()];
            if(leadList.size() > 0) {
                Database.LeadConvert lc = new Database.LeadConvert();
                lc.setLeadId(leadList[0].Id);
                
                LeadStatus convertStatus = [SELECT Id, MasterLabel 
                                            FROM LeadStatus 
                                            WHERE IsConverted = true 
                                            LIMIT 1];
                
                lc.setConvertedStatus(convertStatus.MasterLabel);
                lc.setDoNotCreateOpportunity(TRUE);
                lc.setAccountId(parentAccount.Id);
                
                Database.LeadConvertResult result = Database.convertLead(lc);
                
                if (result.isSuccess()) {
                    Contact candidate =  [SELECT Id, Written_Test_Status__c, Coding_Round_Status__c 
                                          FROM Contact 
                                          WHERE Id = :result.getContactId() 
                                          LIMIT 1];
                    
                    candidate.Written_Test_Status__c = 'Not Started';
                    candidate.Coding_Round_Status__c = 'Not Started';
                    candidate.Exam_Start_Date__c = System.today();
                    update candidate;
                    candidateId = candidate.Id;
                }
            }
            
            return candidateId;
        } else if (contactList.size() > 0) {
            return contactList[0].Id;
        } else {
            return 'invalid';
        }
        
    }
    
    //To get candidate Info
    @AuraEnabled
    public static Contact getCandidateData(String candidateId) {
        
        List<Contact> contactList = [SELECT Id, Email, Hall_Ticket_No__c, Sec_Consumed__c, Written_Test_Status__c, Coding_Round_Status__c 
                                     FROM Contact 
                                     WHERE Id = :candidateId];
        if (contactList.size() > 0) {
            return contactList[0];
        } else {
            return null;
        }
    }
    

    //To get candidate Info
    @AuraEnabled
    public static List<String> getSecretKeys(String candidateId) {
        try{
            Online_Exam_Settings__c coding = Online_Exam_Settings__c.getValues('Coding Round');
            Online_Exam_Settings__c written = Online_Exam_Settings__c.getValues('Written Test');            
            Online_Exam_Settings__c codingTime = Online_Exam_Settings__c.getValues('Coding Exam Duration (Minutes)');            
            Online_Exam_Settings__c writtenTime = Online_Exam_Settings__c.getValues('Written Exam Duration (Minutes)');  
            
            return new List<String> {written.Secret_Key__c, coding.Secret_Key__c,codingTime.Secret_Key__c,writtenTime.Secret_Key__c};
        }
        catch (Exception e) {
            return null;
        }
    }


    //generate both writtenRound and codingRound Questions
    @AuraEnabled
    public static String generateQuestions(String candidateId, String category) {
        
        try {
            Contact candidate = [SELECT Id, Written_Test_Status__c, Coding_Round_Status__c, 
                                 (SELECT Id FROM Candidate_Written_Answers__r), 
                                 (SELECT Id FROM Candidate_Coding_Answers__r) 
                                 FROM Contact 
                                 WHERE Id = :candidateId LIMIT 1];
            if (candidate.Written_Test_Status__c == 'Not Started' && candidate.Candidate_Written_Answers__r.size() == 0) {
                WrittenQuestionAnswerController.insertWrittenQuestions(WrittenQuestionAnswerController.getwrittenQuestions(category), 
                                                                        candidateId );
            } else if(candidate.Written_Test_Status__c == 'Selected' && candidate.Coding_Round_Status__c == 'Not Started' 
                      && candidate.Candidate_Coding_Answers__r.size() == 0) 
            {
                CodingAnswerController.insertCodingQuestions(CodingAnswerController.generateCodingQuestions(category), candidateId );
            }
            return 'success';
        } catch (Exception e) {
            System.debug('CandidateLoginHelper -> generateQuestions :' + e.getLineNumber() + ' ' + e.getMessage());
            return e.getMessage();
        }        
    }
    
    //check if password and hallTicket Matches for adminLogin
    @AuraEnabled
    public static String adminLogin(String candidateHallticket, String password) {
        
        try {
            List<Contact> contactList = [SELECT Id 
                                         FROM Contact 
                                         WHERE Username__c = :candidateHallticket.toUpperCase()];
            if (contactList.size() > 0 && Online_Exam_Settings__c.getValues('Admin Key').Secret_Key__c == password) {
                return contactList[0].Id;
            } else {
                return 'invalid';
            }
        } catch (exception e) {
            System.debug('CandidateLoginHelper -> adminLogin :' + e.getLineNumber() + ' ' + e.getMessage());
            return e.getMessage()+' '+e.getLineNumber();
        }
    }
    
}