force-app/main/default/objects/Candidate_Coding_Answer__c/Candidate_Coding_Answer__c.object-meta.xml
<CustomObject>
    <label>Candidate - Coding Answer</label>
    <nameField>
        <displayFormat>CA - {00000}</displayFormat>
        <label>Candidate - Coding Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidate - Coding Answers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Graduation Branch</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CSE</fullName>
            </value>
            <value>
                <fullName>ECE</fullName>
            </value>
            <value>
                <fullName>EEE</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Coding_Round_Marks__c.field-meta.xml
<CustomField>
    <fullName>Coding_Round_Marks__c</fullName>
    <label>Coding Round Marks</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Coding_Round_Reviewer__c.field-meta.xml
<CustomField>
    <fullName>Coding_Round_Reviewer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Coding Round Reviewer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Coding_Round_Status__c.field-meta.xml
<CustomField>
    <fullName>Coding_Round_Status__c</fullName>
    <label>Coding Round Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Test_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Exam_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Exam_Start_Date__c</fullName>
    <label>Exam Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Manager_Round_Comments__c.field-meta.xml
<CustomField>
    <fullName>Manager_Round_Comments__c</fullName>
    <label>Manager Round Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Post_Graduate_Branch__c.field-meta.xml
<CustomField>
    <fullName>Post_Graduate_Branch__c</fullName>
    <label>Post Graduate Branch</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>M.Sc</fullName>
            </value>
            <value>
                <fullName>M.Tech</fullName>
            </value>
            <value>
                <fullName>M.B.A</fullName>
            </value>
            <value>
                <fullName>MCA</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Tech_Round_Interviewer__c.field-meta.xml
<CustomField>
    <fullName>Tech_Round_Interviewer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User record who interviewed the candidate</description>
    <label>Tech Round Interviewer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Technical_Round_Marks__c.field-meta.xml
<CustomField>
    <fullName>Technical_Round_Marks__c</fullName>
    <label>Technical Round Marks</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Technical_Round_Status__c.field-meta.xml
<CustomField>
    <fullName>Technical_Round_Status__c</fullName>
    <label>Technical Round Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Interview_Status_Picklist</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <label>Username</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Written_Test_Aptitude_Marks__c.field-meta.xml
<CustomField>
    <fullName>Written_Test_Aptitude_Marks__c</fullName>
    <label>Written Test Aptitude Marks</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Written_Test_Marks__c.field-meta.xml
<CustomField>
    <fullName>Written_Test_Marks__c</fullName>
    <formula>Written_Test_Aptitude_Marks__c +  Written_Test_Technical_Marks__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Written Test Marks</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Written_Test_Status__c.field-meta.xml
<CustomField>
    <fullName>Written_Test_Status__c</fullName>
    <label>Written Test Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Test_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Written_Test_Technical_Marks__c.field-meta.xml
<CustomField>
    <fullName>Written_Test_Technical_Marks__c</fullName>
    <label>Written Test Technical Marks</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/Interview_Status_Picklist.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Selected</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <customValue>
        <fullName>On Hold</fullName>
    </customValue>
    <masterLabel>Interview Status Picklist</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Test_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Not Started</fullName>
    </customValue>
    <customValue>
        <fullName>In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Selected</fullName>
    </customValue>
    <customValue>
        <fullName>On Hold</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <masterLabel>Test Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CodingReviewController.cls
/*
Description         :   To store the candidate data, comments, rating, Status after CodingRound Review, Helper for LWC
Test class name     :   
LWC                 :   codingRoundReview
*/

public class CodingReviewController {
    
    // getcandidateData for codingRoundReview for the current logged in User
    @AuraEnabled
    public static List <ExamPortalHelper.codingReviewWrapper> getCandidateCompleteddata() {
        
        List<Contact> contactids = [SELECT Id, Name, Branch__c, Username__c , Coding_Round_Reviewer__c, Coding_Round_Reviewer__r.Name, 
                                    Written_Test_Marks__c, Written_Test_Aptitude_Marks__c, Written_Test_Technical_Marks__c, 
                                    Coding_Round_Status__c, Manager_Round_Comments__c, Coding_Round_Marks__c, Technical_Round_Marks__c, 
                                    Technical_Round_Status__c, Tech_Round_Interviewer__c, Tech_Round_Interviewer__r.Name, Other_Graduation_Branch__c,
                                    Other_PG_Branch__c, Post_Graduate_Branch__c
                                    FROM Contact 
                                    WHERE Written_Test_Status__c = 'Selected' AND
                                    (Coding_Round_Status__c = 'Completed' OR Coding_Round_Status__c = 'Selected' 
                                     OR Coding_Round_Status__c = 'Rejected' OR Coding_Round_Status__c = 'On Hold')
                                     AND Exam_Start_Date__c = TODAY];
        
        List<ExamPortalHelper.codingReviewWrapper> candidates = new List<ExamPortalHelper.codingReviewWrapper>();
        for (Contact contact : contactids) {
            ExamPortalHelper.codingReviewWrapper candidate = new ExamPortalHelper.codingReviewWrapper();
            candidate.id = contact.Id;
            candidate.name = contact.Name;
            if (contact.Post_Graduate_Branch__c != null) {

                if (contact.Post_Graduate_Branch__c == 'Other') {
                    candidate.branch = contact.Other_PG_Branch__c;
                } else {
                    candidate.branch = contact.Post_Graduate_Branch__c;
                }
            } else {
                if (contact.Branch__c == 'Other') {
                    candidate.branch = contact.Other_Graduation_Branch__c;
                } else {
                    candidate.branch = contact.Branch__c;
                }
            }
            //candidate.branch = contact.Branch__c;
            candidate.writtenMarks = String.valueOf(contact.Written_Test_Marks__c);
            candidate.aptitudeMarks = String.valueOf(contact.Written_Test_Aptitude_Marks__c);
            candidate.technicalMarks = String.valueOf(contact.Written_Test_Technical_Marks__c);
            candidate.codingMarks = String.valueOf(contact.Coding_Round_Marks__c);
            candidate.codingRoundStatus = contact.Coding_Round_Status__c;
            candidate.codingReviwedBy = contact.Coding_Round_Reviewer__r.Name;
            candidate.codingRoundReiewerId = contact.Coding_Round_Reviewer__c;
            candidate.technicalRoundStatus = contact.Technical_Round_Status__c;
            candidate.technicalRoundReviewerId = contact.Tech_Round_Interviewer__c;
            candidate.technicalReviewedBy = contact.Tech_Round_Interviewer__r.Name;
            
            candidates.add(candidate);
        }
        return candidates;
    }
    
    // Update CodingRoundReviewer in Contact & Reviewedby in CodingAnswer Records
    @AuraEnabled
    public static String updateCodingReviewer(String candidateId, String userId) {
        List<Candidate_Coding_Answer__c> newCArecords = new List<Candidate_Coding_Answer__c>();
        
        Contact candidate = [SELECT Id, Coding_Round_Reviewer__c 
                             FROM Contact 
                             WHERE Id = :candidateId LIMIT 1];
        candidate.Coding_Round_Reviewer__c = userId;
        try {
            update candidate;            
            return 'success';
        } catch (Exception e) {
            System.debug('CodingReviewController -> updateReviewer :' + e.getLineNumber() + ' ' + e.getMessage());
            return e.getLineNumber() + ' ' + e.getMessage();
        }
    }
    

    //update TechnicalRoundReviewer
    @AuraEnabled
    public static String updateTechnicalReviewer(String candidateId, String userId) {
        List<Candidate_Coding_Answer__c> newCArecords = new List<Candidate_Coding_Answer__c>();
        
        Contact candidate = [SELECT Id, Tech_Round_Interviewer__c 
                             FROM Contact 
                             WHERE Id = :candidateId LIMIT 1];
        candidate.Tech_Round_Interviewer__c = userId;        
        try {
            update candidate;
            return 'success';
        } catch (Exception e) {
            System.debug('CodingReviewController -> updateReviewer :' + e.getLineNumber() + ' ' + e.getMessage());
            return e.getLineNumber() + ' ' + e.getMessage();
        }
    }
}