force-app/main/default/objects/Candidate_Coding_Answer__c/Candidate_Coding_Answer__c.object-meta.xml
<CustomObject>
    <label>Candidate - Coding Answer</label>
    <nameField>
        <displayFormat>CA - {00000}</displayFormat>
        <label>Candidate - Coding Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidate - Coding Answers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate_Coding_Answer__c/fields/CandidateId__c.field-meta.xml
<CustomField>
    <fullName>CandidateId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CandidateId</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Candidate - Coding Answers</relationshipLabel>
    <relationshipName>Candidate_Coding_Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Candidate_Coding_Answer__c/fields/Coding_Round_2_Question__c.field-meta.xml
<CustomField>
    <fullName>Coding_Round_2_Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Coding Round (2) Question</label>
    <referenceTo>Coding_Round_2_Question__c</referenceTo>
    <relationshipLabel>Candidate - Coding Answers</relationshipLabel>
    <relationshipName>Candidate_Coding_Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Candidate_Coding_Answer__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Attempted</fullName>
                <default>true</default>
                <label>Not Attempted</label>
            </value>
            <value>
                <fullName>Just Attempted</fullName>
            </value>
            <value>
                <fullName>Partially Done</fullName>
            </value>
            <value>
                <fullName>Fully Done</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Coding_Round_2_Question__c/Coding_Round_2_Question__c.object-meta.xml
<CustomObject>
    <label>Coding Round (2) Question</label>
    <nameField>
        <displayFormat>CQ-{00000}</displayFormat>
        <label>Coding Round (2) Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coding Round (2) Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Coding_Round_2_Question__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>Java</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Graduation Branch</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CSE</fullName>
            </value>
            <value>
                <fullName>ECE</fullName>
            </value>
            <value>
                <fullName>EEE</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Coding_Round_Reviewer__c.field-meta.xml
<CustomField>
    <fullName>Coding_Round_Reviewer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Coding Round Reviewer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Coding_Round_Status__c.field-meta.xml
<CustomField>
    <fullName>Coding_Round_Status__c</fullName>
    <label>Coding Round Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Test_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Exam_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Exam_Start_Date__c</fullName>
    <label>Exam Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/globalValueSets/Test_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Not Started</fullName>
    </customValue>
    <customValue>
        <fullName>In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Selected</fullName>
    </customValue>
    <customValue>
        <fullName>On Hold</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <masterLabel>Test Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CodingAnswerControllerTest.cls
/*

Apex Class : CodingAnswerController

*/

@isTest
public class CodingAnswerControllerTest {
    @testSetUp
    static void CodingAnswerControllertestSetup() {
        Profile standardPlatformUserProfile = [SELECT Id FROM Profile WHERE Name = 'Standard Platform User' LIMIT 1];
        
        User newUser = new User(
            FirstName = 'test',
            LastName = 'test1',
            Username = 'test1.doe@example.com',
            Email = 'test1.doe@example.com',
            Alias = 'ttes',
            TimeZoneSidKey = 'America/Los_Angeles',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            ProfileId = standardPlatformUserProfile.Id,
            LanguageLocaleKey = 'en_US'
        );
        insert newUser;

        Contact candidate = new Contact();
        candidate.LastName = 'test1';
        candidate.Gender__c = 'Male';
        candidate.Branch__c = 'EEE';
        candidate.Coding_Round_Status__c = 'Completed';
        candidate.Coding_Round_Reviewer__c = newUser.Id;
        candidate.Exam_Start_Date__c = system.Today(); 
        insert candidate;

        List<Coding_Round_2_Question__c> codingQuestions = new List<Coding_Round_2_Question__c>();
        
        Coding_Round_2_Question__c codingques1 = new Coding_Round_2_Question__c();
        codingques1.Category__c = 'Java';
        codingques1.Question__c = 'Write a Program to check whether a number is prime or not.';
        codingQuestions.add(codingques1);

        Coding_Round_2_Question__c codingques2 = new Coding_Round_2_Question__c();
        codingques2.Category__c = 'C';
        codingques2.Question__c = 'Write a program to calculate Compound Interest.';
        codingQuestions.add(codingques2);

        Coding_Round_2_Question__c codingques3 = new Coding_Round_2_Question__c();
        codingques3.Category__c = 'Java';
        codingques3.Question__c = 'Write a program to Factorial of a Number.';
        codingQuestions.add(codingques3);

        Coding_Round_2_Question__c codingques4 = new Coding_Round_2_Question__c();
        codingques4.Category__c = 'Java';
        codingques4.Question__c = 'Write a Program to reverse a number.';
        codingQuestions.add(codingques4);

        insert codingQuestions;

        List<Candidate_Coding_Answer__c> codingAnswers = new List<Candidate_Coding_Answer__c>();
        
        Candidate_Coding_Answer__c codingAns1 = new Candidate_Coding_Answer__c();
        codingAns1.CandidateId__c = candidate.Id;
        codingAns1.Coding_Round_2_Question__c = codingQuestions[0].Id;
        codingAns1.Rating__c = '';
        codingAns1.Response__c = 'answer 1';
        codingAns1.Status__c = 'Not Attempted';
        codingAnswers.add(codingAns1);

        Candidate_Coding_Answer__c codingAns2 = new Candidate_Coding_Answer__c();
        codingAns2.CandidateId__c = candidate.Id;
        codingAns2.Coding_Round_2_Question__c = codingQuestions[1].Id;
        codingAns2.Rating__c = '1';
        codingAns2.Response__c = 'answer 2';
        codingAns2.Status__c = 'Not Attempted';
        codingAnswers.add(codingAns2);

        Candidate_Coding_Answer__c codingAns3 = new Candidate_Coding_Answer__c();
        codingAns3.CandidateId__c = candidate.Id;
        codingAns3.Coding_Round_2_Question__c = codingQuestions[2].Id;
        codingAns3.Rating__c = '2';
        codingAns3.Response__c = 'answer 3';
        codingAns3.Status__c = 'Not Attempted';
        codingAnswers.add(codingAns3);

        insert codingAnswers;
    }
     @isTest
    static void CodingAnswerControllerTestMethod () {
        Contact candidate = [SELECT Id, Coding_Round_Reviewer__c from Contact limit 1];
        List<Coding_Round_2_Question__c> codingQuestions= [SELECT Id, Question__c, Category__c FROM  Coding_Round_2_Question__c];
        List<Candidate_Coding_Answer__c> codingAnswers = [SELECT CandidateId__c, Rating__c, Response__c,
                                                          Coding_Round_2_Question__c, Status__c FROM Candidate_Coding_Answer__c];
        CodingAnswerController.shuffleCodingQuestions(codingQuestions,3);
        CodingAnswerController.generateCodingQuestions('Java');
        CodingAnswerController.insertCodingQuestions(codingQuestions, candidate.Id);
        CodingAnswerController.getCandidateCodingRecords(candidate.Id);
        CodingAnswerController.storeCodingRoundStatus('Selected', candidate.Id);
        CodingAnswerController.getCandidateData(candidate.Id);
        
        List<Map<String, String>> info = new List<Map<String, String>>();
        for (Integer i = 0; i < 3; i++) {
             Map<String, String> recordMap = new Map<String, String>{
                'CArecordId'=> String.valueOf(codingAnswers[i].Id),
                'CandidateId' => String.valueOf(candidate.Id),
                'id'=> String.valueOf(codingAnswers[i].Coding_Round_2_Question__c),
                'response'=> String.valueOf(codingAnswers[i].Response__c),
                'status'=> String.valueOf(codingAnswers[i].Status__c),
                'comments' => 'commentss',
                'reviewedby'=> String.valueOf(candidate.Coding_Round_Reviewer__c),
                'rating'=> String.valueOf(codingAnswers[i].Rating__c)
            };
            info.add(recordMap);
            
        }
        CodingAnswerController.storeCodingInformation(info);
    }
}