force-app/main/default/objects/Candidate_Coding_Answer__c/Candidate_Coding_Answer__c.object-meta.xml
<CustomObject>
    <label>Candidate - Coding Answer</label>
    <nameField>
        <displayFormat>CA - {00000}</displayFormat>
        <label>Candidate - Coding Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidate - Coding Answers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate_Coding_Answer__c/fields/CandidateId__c.field-meta.xml
<CustomField>
    <fullName>CandidateId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CandidateId</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Candidate - Coding Answers</relationshipLabel>
    <relationshipName>Candidate_Coding_Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Candidate_Coding_Answer__c/fields/Coding_Round_2_Question__c.field-meta.xml
<CustomField>
    <fullName>Coding_Round_2_Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Coding Round (2) Question</label>
    <referenceTo>Coding_Round_2_Question__c</referenceTo>
    <relationshipLabel>Candidate - Coding Answers</relationshipLabel>
    <relationshipName>Candidate_Coding_Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Candidate_Coding_Answer__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Attempted</fullName>
                <default>true</default>
                <label>Not Attempted</label>
            </value>
            <value>
                <fullName>Just Attempted</fullName>
            </value>
            <value>
                <fullName>Partially Done</fullName>
            </value>
            <value>
                <fullName>Fully Done</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Coding_Round_2_Question__c/Coding_Round_2_Question__c.object-meta.xml
<CustomObject>
    <label>Coding Round (2) Question</label>
    <nameField>
        <displayFormat>CQ-{00000}</displayFormat>
        <label>Coding Round (2) Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coding Round (2) Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Coding_Round_2_Question__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>Java</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Coding_Round_Marks__c.field-meta.xml
<CustomField>
    <fullName>Coding_Round_Marks__c</fullName>
    <label>Coding Round Marks</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Coding_Round_Reviewer__c.field-meta.xml
<CustomField>
    <fullName>Coding_Round_Reviewer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Coding Round Reviewer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Coding_Round_Status__c.field-meta.xml
<CustomField>
    <fullName>Coding_Round_Status__c</fullName>
    <label>Coding Round Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Test_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Technical_Round_Status__c.field-meta.xml
<CustomField>
    <fullName>Technical_Round_Status__c</fullName>
    <label>Technical Round Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Interview_Status_Picklist</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Recruiting_Manager__c.field-meta.xml
<CustomField>
    <fullName>Recruiting_Manager__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Recruiting Manager</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/Interview_Status_Picklist.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Selected</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <customValue>
        <fullName>On Hold</fullName>
    </customValue>
    <masterLabel>Interview Status Picklist</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Test_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Not Started</fullName>
    </customValue>
    <customValue>
        <fullName>In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Selected</fullName>
    </customValue>
    <customValue>
        <fullName>On Hold</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <masterLabel>Test Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CodingAnswerController.cls
/*
Description			:	To generate questions for CodingTest and store the answers of candidates and change status after review.
Test class name		:	
LWC					:	ep_codingTest
*/

public without sharing class CodingAnswerController {
    
    // To shuffle the entire list of questions and return desired number of questions  
    public static List<Coding_Round_2_Question__c> shuffleCodingQuestions(List<Coding_Round_2_Question__c> originalList, Integer n) {
        List<Coding_Round_2_Question__c> shuffledList = new List<Coding_Round_2_Question__c>();
        
        if (originalList.size() <= n) {
            return originalList;
        }
        
        while (shuffledList.size() < n) {
            Integer index = Math.mod(Math.abs(Crypto.getRandomInteger()), originalList.size());
            shuffledList.add(originalList.remove(index));
        }
        
        return shuffledList;
    }
    
    // To generate 3 Coding Round Questions
    public static List<Coding_Round_2_Question__c> generateCodingQuestions(String category) {
        List<Coding_Round_2_Question__c> allQuestions = new List<Coding_Round_2_Question__c>();
        
        List<Coding_Round_2_Question__c> allcodingQuestions = [SELECT Question__c, Category__c 
                                                               FROM Coding_Round_2_Question__c 
                                                               WHERE Category__c = :category];
        allQuestions.addAll(shuffleCodingQuestions(allcodingQuestions, 3));
        
        return allQuestions;
    }
    
    // To insert Coding Round Question Records for given CandidateId    
    public static String insertCodingQuestions(List<Coding_Round_2_Question__c> info,String candidateId) {
        List<Candidate_Coding_Answer__c> CArecords = new List<Candidate_Coding_Answer__c>();
        
        for (Coding_Round_2_Question__c eachrecord : info) {
            Candidate_Coding_Answer__c CArecord = new Candidate_Coding_Answer__c();
            CArecord.CandidateId__c = candidateId;
            CArecord.Coding_Round_2_Question__c = eachrecord.Id;
            CArecord.Response__c = '';
            CArecords.add(CArecord);
        }
        
        try {
            insert CArecords;
            return 'success';
        } catch (Exception e) {
            System.debug('CodingAnswerController -> insertCodingQuestions :' + e.getLineNumber() + ' ' + e.getMessage());
            return e.getMessage();
        }
    }
    
    // To fetch available codingRound Records for given candidateId
    @AuraEnabled
    public static List<Candidate_Coding_Answer__c> getCandidateCodingRecords(String candidateId) {
        List<Candidate_Coding_Answer__c> codingAnswerList = [SELECT Id, Coding_Round_2_Question__r.Question__c, Status__c, Comments__c, 
                                                             Rating__c, Coding_Round_2_Question__r.Category__c, Response__c ,
                                                             CandidateId__r.Coding_Round_Reviewer__r.Name
                                                             FROM Candidate_Coding_Answer__c 
                                                             WHERE CandidateId__c = :candidateId];
        if (!codingAnswerList.isEmpty()) {
            return codingAnswerList;
        } else {
            return null;
        }
    }
    
    // Store the coding Test info of candidate
    @AuraEnabled
    public static String storeCodingInformation(List<Map<String, String>> info) {
        system.debug(info);
        Integer codingRoundMarks = 0;
        String candidateId;
        List<Candidate_Coding_Answer__c> CArecords = new List<Candidate_Coding_Answer__c>();
        System.debug('info:::'+info);
        
        for(Map<String, String> eachrecord : info) {
            Candidate_Coding_Answer__c CArecord = new Candidate_Coding_Answer__c();
            CArecord.Id = eachrecord.get('CArecordId');
            CArecord.CandidateId__c = eachrecord.get('CandidateId');
            candidateId = CArecord.CandidateId__c;
            CArecord.Coding_Round_2_Question__c = eachrecord.get('id');
            CArecord.Response__c = eachrecord.get('response');
            CArecord.Status__c = eachrecord.get('status');
            CArecord.Comments__c = eachrecord.get('comments');
            CARecord.Rating__c = eachrecord.get('rating');
            codingRoundMarks += (CARecord.Rating__c == null ? 0 : Integer.valueOf(CARecord.Rating__c));
            CArecords.add(CArecord);
        }
        
        Contact contact = [SELECT Id, Coding_Round_Marks__c 
                           FROM Contact 
                           WHERE Id = :candidateId];
        contact.Coding_Round_Marks__c = (Decimal.valueOf(codingRoundMarks) / Decimal.valueOf(3)).setScale(2);
        try {
            System.debug('CArecords:::'+CArecords);
            update CArecords;
            update contact;
            return 'success';
        } catch (Exception e) {
            System.debug('CodingAnswerController -> storeCodingInformation :' + e.getLineNumber() + ' ' + e.getMessage());
            return e.getMessage();
        }
    }
    
    // Store CodingRound status after Review
    @AuraEnabled
    public static String storeCodingRoundStatus(String status, String candidateId) {
        Contact contact = [SELECT Id, Coding_Round_Status__c 
                           FROM Contact 
                           WHERE Id = :candidateId LIMIT 1];
        contact.Coding_Round_Status__c = status;
        try {
            update contact;
            return 'success';
        } catch(Exception e) {
            System.debug('CodingAnswerController -> storeCodingRoundRating :' + e.getLineNumber() + ' ' + e.getMessage());
            return e.getMessage();
        }
    }
    
    // Fetch candidate data
    @AuraEnabled
    public static Contact getCandidateData(String candidateId) {
        
        Contact contact = [SELECT Id, Coding_Round_Reviewer__c, Coding_Round_Status__c, Technical_Round_Status__c 
                           FROM Contact 
                           WHERE Id = :candidateId];
        return contact;
    }

    @AuraEnabled
    public static User getUserData(String userId){
        User user = [SELECT Recruiting_Manager__c FROM User WHERE Id =: userId];
        return user;
    }
}