force-app/main/default/objects/Candidate_Coding_Answer__c/Candidate_Coding_Answer__c.object-meta.xml
<CustomObject>
    <label>Candidate - Coding Answer</label>
    <nameField>
        <displayFormat>CA - {00000}</displayFormat>
        <label>Candidate - Coding Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidate - Coding Answers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate_Coding_Answer__c/fields/CandidateId__c.field-meta.xml
<CustomField>
    <fullName>CandidateId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CandidateId</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Candidate - Coding Answers</relationshipLabel>
    <relationshipName>Candidate_Coding_Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Candidate_Coding_Answer__c/fields/Coding_Round_2_Question__c.field-meta.xml
<CustomField>
    <fullName>Coding_Round_2_Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Coding Round (2) Question</label>
    <referenceTo>Coding_Round_2_Question__c</referenceTo>
    <relationshipLabel>Candidate - Coding Answers</relationshipLabel>
    <relationshipName>Candidate_Coding_Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Candidate_Coding_Answer__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Attempted</fullName>
                <default>true</default>
                <label>Not Attempted</label>
            </value>
            <value>
                <fullName>Just Attempted</fullName>
            </value>
            <value>
                <fullName>Partially Done</fullName>
            </value>
            <value>
                <fullName>Fully Done</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Coding_Round_2_Question__c/Coding_Round_2_Question__c.object-meta.xml
<CustomObject>
    <label>Coding Round (2) Question</label>
    <nameField>
        <displayFormat>CQ-{00000}</displayFormat>
        <label>Coding Round (2) Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coding Round (2) Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Coding_Round_2_Question__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>Java</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Coding_Round_Status__c.field-meta.xml
<CustomField>
    <fullName>Coding_Round_Status__c</fullName>
    <label>Coding Round Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Test_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/End_Test_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Test_Time__c</fullName>
    <label>End Test Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Exam_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Exam_Start_Date__c</fullName>
    <label>Exam Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Sec_Consumed__c.field-meta.xml
<CustomField>
    <fullName>Sec_Consumed__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Consumed Seconds</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Start_Test_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Test_Time__c</fullName>
    <label>Start Test Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Written_Test_Status__c.field-meta.xml
<CustomField>
    <fullName>Written_Test_Status__c</fullName>
    <label>Written Test Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Test_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Test_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Not Started</fullName>
    </customValue>
    <customValue>
        <fullName>In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Selected</fullName>
    </customValue>
    <customValue>
        <fullName>On Hold</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <masterLabel>Test Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CodingQuestionnaireControllerTest.cls
@isTest
public class CodingQuestionnaireControllerTest {
  @testSetup
    static void CodingQuestionnaireControllerTestsetup() {
        // Setup any necessary test data here, if required.
        Contact candidate = new Contact(LastName = 'test1',
                                        Gender__c = 'Male',
                                        Written_Test_Status__c = 'Selected',
                                        Coding_Round_Status__c = 'Completed',
                                        Sec_Consumed__c = 2,
                                        Start_Test_Time__c = datetime.now().addSeconds(-40).time(),
										End_Test_Time__c = datetime.now().addSeconds(-20).time(),
                                        Exam_Start_Date__c = system.Today());
        insert candidate;
        
        List<Coding_Round_2_Question__c> codingQuestions = new List<Coding_Round_2_Question__c>();
        
        Coding_Round_2_Question__c codingques1 = new Coding_Round_2_Question__c();
        codingques1.Category__c = 'C';
        codingques1.Question__c = 'Write a Program to check whether a number is prime or not.';
        codingQuestions.add(codingques1);

        Coding_Round_2_Question__c codingques2 = new Coding_Round_2_Question__c();
        codingques2.Category__c = 'C';
        codingques2.Question__c = 'Write a program to calculate Compound Interest.';
        codingQuestions.add(codingques2);

        Coding_Round_2_Question__c codingques3 = new Coding_Round_2_Question__c();
        codingques3.Category__c = 'C';
        codingques3.Question__c = 'Write a program to Factorial of a Number.';
        codingQuestions.add(codingques3);
        
        insert codingQuestions;
 
        List<Candidate_Coding_Answer__c> codingAnswers = new List<Candidate_Coding_Answer__c>();
        
        Candidate_Coding_Answer__c codingAns1 = new Candidate_Coding_Answer__c();
        codingAns1.CandidateId__c = candidate.Id;
        codingAns1.Coding_Round_2_Question__c = codingQuestions[0].Id;
        codingAns1.Rating__c = '';
        codingAns1.Response__c = 'answer 1';
        codingAns1.Status__c = 'Not Attempted';
        codingAnswers.add(codingAns1);

        Candidate_Coding_Answer__c codingAns2 = new Candidate_Coding_Answer__c();
        codingAns2.CandidateId__c = candidate.Id;
        codingAns2.Coding_Round_2_Question__c = codingQuestions[1].Id;
        codingAns2.Rating__c = '1';
        codingAns2.Response__c = 'answer 2';
        codingAns2.Status__c = 'Not Attempted';
        codingAnswers.add(codingAns2);

        Candidate_Coding_Answer__c codingAns3 = new Candidate_Coding_Answer__c();
        codingAns3.CandidateId__c = candidate.Id;
        codingAns3.Coding_Round_2_Question__c = codingQuestions[2].Id;
        codingAns3.Rating__c = '2';
        codingAns3.Response__c = 'answer 3';
        codingAns3.Status__c = 'Not Attempted';
        codingAnswers.add(codingAns3);

        insert codingAnswers;
    }

    @isTest
    static void CodingQuestionnaireControllerTestMethod() {
        Test.startTest();
            Contact candidate = [SELECT Id from Contact limit 1];
        	List<Candidate_Coding_Answer__c> writtenAnswers = [SELECT Id,CandidateId__c,Response__c, Status__c, 
                                                               Rating__c, Coding_Round_2_Question__c 
                                                               FROM Candidate_Coding_Answer__c 
                                                               WHERE CandidateId__c =: candidate.Id];
            PageReference testPageRef = Page.CodingQuestionnaire;
        	Test.setCurrentPage(testPageRef);
            ApexPages.currentPage().getParameters().put('key', ExamPortalHelper.encryptKey(candidate.Id)[1]);
        	CodingQuestionnaireController codeReviewPage = new CodingQuestionnaireController();
        
        	PageReference testPageRef1 = Page.CodingQuestionnaire;
        	Test.setCurrentPage(testPageRef1);
            ApexPages.currentPage().getParameters().put('key', ExamPortalHelper.encryptKey(candidate.Id + '#' + 'true')[1]);
        	CodingQuestionnaireController.updateStatus(candidate.Id);
        	CodingQuestionnaireController codeReviewPage1 = new CodingQuestionnaireController();
        	
        	codeReviewPage1.saveData();
        Test.stopTest();       
    }
}