force-app/main/default/objects/Candidate_Written_Answer__c/Candidate_Written_Answer__c.object-meta.xml
<CustomObject>
    <label>Candidate - Written Answer</label>
    <nameField>
        <displayFormat>CW-{00000}</displayFormat>
        <label>Candidate - Written Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidate - Written Answers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate_Written_Answer__c/fields/CandidateId__c.field-meta.xml
<CustomField>
    <fullName>CandidateId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CandidateId</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Candidate - Written Answers</relationshipLabel>
    <relationshipName>Candidate_Written_Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Candidate_Written_Answer__c/fields/Written_Round_1_Question__c.field-meta.xml
<CustomField>
    <fullName>Written_Round_1_Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Written Round (1) Question</label>
    <referenceTo>Written_Round_1_Question__c</referenceTo>
    <relationshipLabel>Candidate - Written Answers</relationshipLabel>
    <relationshipName>Candidate_Written_Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/End_Test_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Test_Time__c</fullName>
    <label>End Test Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Exam_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Exam_Start_Date__c</fullName>
    <label>Exam Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Sec_Consumed__c.field-meta.xml
<CustomField>
    <fullName>Sec_Consumed__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Consumed Seconds</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Start_Test_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Test_Time__c</fullName>
    <label>Start Test Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Written_Test_Status__c.field-meta.xml
<CustomField>
    <fullName>Written_Test_Status__c</fullName>
    <label>Written Test Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Test_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Written_Round_1_Question__c/Written_Round_1_Question__c.object-meta.xml
<CustomObject>
    <label>Written Round (1) Question</label>
    <nameField>
        <displayFormat>WQ-{00000}</displayFormat>
        <label>Written Round (1) Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Written Round (1) Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Written_Round_1_Question__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Category_picklist</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Written_Round_1_Question__c/fields/Option_1__c.field-meta.xml
<CustomField>
    <fullName>Option_1__c</fullName>
    <label>Option 1</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Written_Round_1_Question__c/fields/Option_2__c.field-meta.xml
<CustomField>
    <fullName>Option_2__c</fullName>
    <label>Option 2</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Written_Round_1_Question__c/fields/Option_3__c.field-meta.xml
<CustomField>
    <fullName>Option_3__c</fullName>
    <label>Option 3</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Written_Round_1_Question__c/fields/Option_4__c.field-meta.xml
<CustomField>
    <fullName>Option_4__c</fullName>
    <label>Option 4</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Written_Round_1_Question__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Question</label>
    <length>32627</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Written_Round_1_Question__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Technical</fullName>
            </value>
            <value>
                <fullName>Aptitude</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Category_picklist.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Percentage</fullName>
    </customValue>
    <customValue>
        <fullName>Calendar</fullName>
    </customValue>
    <customValue>
        <fullName>Average</fullName>
    </customValue>
    <customValue>
        <fullName>Clock</fullName>
    </customValue>
    <customValue>
        <fullName>Profit and Loss</fullName>
    </customValue>
    <customValue>
        <fullName>Simple Interest</fullName>
    </customValue>
    <customValue>
        <fullName>Problems on Ages</fullName>
    </customValue>
    <customValue>
        <fullName>Time and Distance</fullName>
    </customValue>
    <customValue>
        <fullName>Height and Distance</fullName>
    </customValue>
    <customValue>
        <fullName>Boats and Streams</fullName>
    </customValue>
    <customValue>
        <fullName>C</fullName>
    </customValue>
    <customValue>
        <fullName>Java</fullName>
    </customValue>
    <customValue>
        <fullName>Pipes and Cistern</fullName>
    </customValue>
    <masterLabel>Category picklist</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Test_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Not Started</fullName>
    </customValue>
    <customValue>
        <fullName>In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Selected</fullName>
    </customValue>
    <customValue>
        <fullName>On Hold</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <masterLabel>Test Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/QuestionnaireControllerTest.cls
@isTest
public class QuestionnaireControllerTest {
    @testSetup
    static void QuestionnaireControllerTestsetup() {
        // Setup any necessary test data here, if required.
        Contact candidate = new Contact(LastName = 'test1',
                                        Gender__c = 'Male',
                                        Written_Test_Status__c = 'Completed',
                                        Sec_Consumed__c = 2,
                                        Start_Test_Time__c = datetime.now().addSeconds(-40).time(),
										End_Test_Time__c = datetime.now().addSeconds(-20).time(),
                                        Exam_Start_Date__c = system.Today());
        insert candidate;
        
        List<Written_Round_1_Question__c> writtenQuestions = new List<Written_Round_1_Question__c>();
        for(Integer i=0; i< 20; i++){
            Written_Round_1_Question__c writtenQues1 = new Written_Round_1_Question__c();
            if(i < 2){
                writtenQues1.Category__c = 'Height and Distance';
            }else if(i >= 2 && i < 4){
                writtenQues1.Category__c = 'Calendar';
            }else if(i >= 4 && i < 6){
                writtenQues1.Category__c = 'Average';
            }else if(i >= 6 && i < 8){
                writtenQues1.Category__c = 'Clock';
            }else if(i >= 8 && i < 10){
                writtenQues1.Category__c = 'Percentage';
            }else if(i >= 10 && i < 15){
                writtenQues1.Category__c = 'C';
            }else if(i >= 15){
                writtenQues1.Category__c = 'Java';
            }
            writtenQues1.Option_1__c = '1'+i;
            writtenQues1.Option_2__c = '2'+i;
            writtenQues1.Option_3__c = '3'+i;
            writtenQues1.Option_4__c = '4'+i;
            writtenQues1.Answer__c = 'answer'; 
            writtenQues1.Question__c = '1+2 = ?'+i;
            if(i < 10){
                writtenQues1.Type__c = 'Aptitude';
            }else{
                writtenQues1.Type__c = 'Technical';
            }
            writtenQuestions.add(writtenQues1);
        }

        insert writtenQuestions;
 
        List<Candidate_Written_Answer__c> writtenAnswers = new List<Candidate_Written_Answer__c>();
        for(Integer i = 0; i< 20; i++){
        	writtenAnswers.add(new Candidate_Written_Answer__c(CandidateId__c = candidate.Id, Response__c = 'answer', Written_Round_1_Question__c = writtenQuestions[i].Id));//, Written_Round_1_Question__c = ));            
        }
        insert writtenAnswers;
    }

    @isTest
    static void QuestionnaireControllerTestMethod() {
        Test.startTest();
            Contact candidate = [SELECT Id from Contact limit 1];
        	List<Candidate_Written_Answer__c> writtenAnswers = [SELECT Id,CandidateId__c,Response__c, Written_Round_1_Question__c 
                                                                from Candidate_Written_Answer__c where CandidateId__c =: candidate.Id];
            PageReference testPageRef = Page.Questionnaire;
        	Test.setCurrentPage(testPageRef);
            ApexPages.currentPage().getParameters().put('key', ExamPortalHelper.encryptKey(candidate.Id)[1]);
        	QuestionnaireController codeReviewPage = new QuestionnaireController();
        
        	PageReference testPageRef1 = Page.Questionnaire;
        	Test.setCurrentPage(testPageRef1);
            ApexPages.currentPage().getParameters().put('key', ExamPortalHelper.encryptKey(candidate.Id + '#' + 'true')[1]);
        	QuestionnaireController codeReviewPage1 = new QuestionnaireController();
        	QuestionnaireController.updateStatus(candidate.Id);
        	codeReviewPage1.storeMarks(writtenAnswers);
        	codeReviewPage1.saveData();
        Test.stopTest();       
    }
}