force-app/main/default/objects/Contact/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Graduation Branch</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CSE</fullName>
            </value>
            <value>
                <fullName>ECE</fullName>
            </value>
            <value>
                <fullName>EEE</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Coding_Round_Reviewer__c.field-meta.xml
<CustomField>
    <fullName>Coding_Round_Reviewer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Coding Round Reviewer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Coding_Round_Status__c.field-meta.xml
<CustomField>
    <fullName>Coding_Round_Status__c</fullName>
    <label>Coding Round Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Test_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Exam_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Exam_Start_Date__c</fullName>
    <label>Exam Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Post_Graduate_Branch__c.field-meta.xml
<CustomField>
    <fullName>Post_Graduate_Branch__c</fullName>
    <label>Post Graduate Branch</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>M.Sc</fullName>
            </value>
            <value>
                <fullName>M.Tech</fullName>
            </value>
            <value>
                <fullName>M.B.A</fullName>
            </value>
            <value>
                <fullName>MCA</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Written_Test_Status__c.field-meta.xml
<CustomField>
    <fullName>Written_Test_Status__c</fullName>
    <label>Written Test Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Test_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Test_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Not Started</fullName>
    </customValue>
    <customValue>
        <fullName>In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Selected</fullName>
    </customValue>
    <customValue>
        <fullName>On Hold</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <masterLabel>Test Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CodingReviewControllerTest.cls
/*

Apex class: CodingReviewController

*/

@isTest
public class CodingReviewControllerTest {
    @testSetUp
    static void CodingReviewControllertestSetup() {
        Profile standardPlatformUserProfile = [SELECT Id FROM Profile WHERE Name = 'Standard Platform User' LIMIT 1];
        
        User newUser = new User(
            FirstName = 'test',
            LastName = 'test1',
            Username = 'test1.doe@example.com',
            Email = 'test1.doe@example.com',
            Alias = 'ttes',
            TimeZoneSidKey = 'America/Los_Angeles',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            ProfileId = standardPlatformUserProfile.Id,
            LanguageLocaleKey = 'en_US'
        );
        insert newUser;

        List<Contact> candidates = new List<Contact>();

        Contact candidate1 = new Contact();
        candidate1.LastName = 'test1';
        candidate1.Gender__c = 'Male';
        candidate1.Branch__c = 'EEE';
        candidate1.Post_Graduate_Branch__c = 'MCA';
        candidate1.Written_Test_Status__c = 'Selected';
        candidate1.Coding_Round_Status__c = 'Completed';
        candidate1.Coding_Round_Reviewer__c = newUser.Id;
        candidate1.Exam_Start_Date__c = system.Today(); 
        candidates.add(candidate1);

        Contact candidate2 = new Contact();
        candidate2.LastName = 'test2';
        candidate2.Gender__c = 'Female';
        candidate2.Post_Graduate_Branch__c = 'Other';
        candidate2.Other_PG_Branch__c = 'MCAA';
        candidate2.Written_Test_Status__c = 'Selected';
        candidate2.Coding_Round_Status__c = 'Selected';
        candidate2.Coding_Round_Reviewer__c = newUser.Id;
        candidate2.Exam_Start_Date__c = system.Today(); 
        candidates.add(candidate2);

        Contact candidate3 = new Contact();
        candidate3.LastName = 'test3';
        candidate3.Gender__c = 'Male';
        candidate3.Branch__c = 'Other';
        candidate3.Other_Graduation_Branch__c = 'AIML';
        candidate3.Written_Test_Status__c = 'Selected';
        candidate3.Coding_Round_Status__c = 'On Hold';
        candidate3.Coding_Round_Reviewer__c = newUser.Id;
        candidate3.Exam_Start_Date__c = system.Today(); 
        candidates.add(candidate3);

        Contact candidate = new Contact();
        candidate.LastName = 'test4';
        candidate.Gender__c = 'Female';
        candidate.Branch__c = 'CSE';
        candidate.Written_Test_Status__c = 'Selected';
        candidate.Coding_Round_Status__c = 'Rejected';
        candidate.Coding_Round_Reviewer__c = newUser.Id;
        candidate.Exam_Start_Date__c = system.Today(); 
        candidates.add(candidate);

        insert candidates;
    }
    @isTest
    static void CodingReviewControllerTestMethod () {
        User newUser = [SELECT Id FROM User limit 1];
        List<Contact> candidates = [SELECT Id, LastName FROM Contact];
        CodingReviewController.getCandidateCompleteddata();
        CodingReviewController.updateCodingReviewer(candidates[0].Id,newUser.Id);
        CodingReviewController.updateTechnicalReviewer(candidates[0].Id, newUser.Id);
    }
}