force-app/main/default/objects/Contact/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Graduation Branch</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CSE</fullName>
            </value>
            <value>
                <fullName>ECE</fullName>
            </value>
            <value>
                <fullName>EEE</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Exam_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Exam_Start_Date__c</fullName>
    <label>Exam Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Post_Graduate_Branch__c.field-meta.xml
<CustomField>
    <fullName>Post_Graduate_Branch__c</fullName>
    <label>Post Graduate Branch</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>M.Sc</fullName>
            </value>
            <value>
                <fullName>M.Tech</fullName>
            </value>
            <value>
                <fullName>M.B.A</fullName>
            </value>
            <value>
                <fullName>MCA</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Written_Round_1_Question__c/Written_Round_1_Question__c.object-meta.xml
<CustomObject>
    <label>Written Round (1) Question</label>
    <nameField>
        <displayFormat>WQ-{00000}</displayFormat>
        <label>Written Round (1) Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Written Round (1) Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Written_Round_1_Question__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Category_picklist</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Written_Round_1_Question__c/fields/Option_1__c.field-meta.xml
<CustomField>
    <fullName>Option_1__c</fullName>
    <label>Option 1</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Written_Round_1_Question__c/fields/Option_2__c.field-meta.xml
<CustomField>
    <fullName>Option_2__c</fullName>
    <label>Option 2</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Written_Round_1_Question__c/fields/Option_3__c.field-meta.xml
<CustomField>
    <fullName>Option_3__c</fullName>
    <label>Option 3</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Written_Round_1_Question__c/fields/Option_4__c.field-meta.xml
<CustomField>
    <fullName>Option_4__c</fullName>
    <label>Option 4</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Written_Round_1_Question__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Question</label>
    <length>32627</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Written_Round_1_Question__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Technical</fullName>
            </value>
            <value>
                <fullName>Aptitude</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Category_picklist.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Percentage</fullName>
    </customValue>
    <customValue>
        <fullName>Calendar</fullName>
    </customValue>
    <customValue>
        <fullName>Average</fullName>
    </customValue>
    <customValue>
        <fullName>Clock</fullName>
    </customValue>
    <customValue>
        <fullName>Profit and Loss</fullName>
    </customValue>
    <customValue>
        <fullName>Simple Interest</fullName>
    </customValue>
    <customValue>
        <fullName>Problems on Ages</fullName>
    </customValue>
    <customValue>
        <fullName>Time and Distance</fullName>
    </customValue>
    <customValue>
        <fullName>Height and Distance</fullName>
    </customValue>
    <customValue>
        <fullName>Boats and Streams</fullName>
    </customValue>
    <customValue>
        <fullName>C</fullName>
    </customValue>
    <customValue>
        <fullName>Java</fullName>
    </customValue>
    <customValue>
        <fullName>Pipes and Cistern</fullName>
    </customValue>
    <masterLabel>Category picklist</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/WrittenQuestionAnswerControllerTest.cls
/*

Apex class : WrittenQuestionAnswerConstroller

*/

@isTest
public class WrittenQuestionAnswerControllerTest {
    @testSetUp
    static void WrittenQuestionAnswerControllerTestsetup() {
        Contact candidate = new Contact();
        candidate.LastName = 'test1';
        candidate.Gender__c = 'Male';
        candidate.Branch__c = 'EEE';
        candidate.Post_Graduate_Branch__c = 'MCA';
        candidate.Exam_Start_Date__c = system.Today(); 

        insert candidate;

        List<Written_Round_1_Question__c> writtenQuestions = new List<Written_Round_1_Question__c>();
        for(Integer i=0; i< 40; i++){
            Written_Round_1_Question__c writtenQues1 = new Written_Round_1_Question__c();
            if(i < 4){
                writtenQues1.Category__c = 'Height and Distance';
            }else if(i >= 4 && i < 8){
                writtenQues1.Category__c = 'Calendar';
            }else if(i >= 8 && i < 13){
                writtenQues1.Category__c = 'Average';
            }else if(i >= 13 && i < 17){
                writtenQues1.Category__c = 'Clock';
            }else if(i >= 17 && i < 20){
                writtenQues1.Category__c = 'Percentage';
            }else if(i >= 20 && i < 30){
                writtenQues1.Category__c = 'C';
            }else if(i >= 30){
                writtenQues1.Category__c = 'Java';
            }
            writtenQues1.Option_1__c = '1'+i;
            writtenQues1.Option_2__c = '2'+i;
            writtenQues1.Option_3__c = '3'+i;
            writtenQues1.Option_4__c = '4'+i;
            writtenQues1.Question__c = '1+2 = ?'+i;
            if(i < 20){
                writtenQues1.Type__c = 'Aptitude';
            }else{
                writtenQues1.Type__c = 'Technical';
            }
            writtenQuestions.add(writtenQues1);
        }

        insert writtenQuestions;
    }

    @IsTest
    static void WrittenQuestionAnswerControllerTestMethod () {
        Contact candidate = [SELECT Id FROM Contact limit 1];
        WrittenQuestionAnswerController.getwrittenQuestions('C & Java');
        WrittenQuestionAnswerController.insertWrittenQuestions(WrittenQuestionAnswerController.getwrittenQuestions('C & Java'), candidate.Id);
    }
}