force-app/main/default/objects/Contact/fields/Coding_Round_Status__c.field-meta.xml
<CustomField>
    <fullName>Coding_Round_Status__c</fullName>
    <label>Coding Round Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Test_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Exam_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Exam_Start_Date__c</fullName>
    <label>Exam Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Written_Test_Status__c.field-meta.xml
<CustomField>
    <fullName>Written_Test_Status__c</fullName>
    <label>Written Test Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Test_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Test_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Not Started</fullName>
    </customValue>
    <customValue>
        <fullName>In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Selected</fullName>
    </customValue>
    <customValue>
        <fullName>On Hold</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <masterLabel>Test Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CodingRoundReviewControllerTest.cls
@isTest
public class CodingRoundReviewControllerTest {

    @testSetup
    static void CodingRoundReviewControllerTestsetup() {
        // Setup any necessary test data here, if required.
        Contact candidate = new Contact(LastName = 'test1',
                                        Gender__c = 'Male',
                                        Written_Test_Status__c = 'Selected',
                                        Coding_Round_Status__c = 'Not Started',
                                        Exam_Start_Date__c = system.Today());
        insert candidate;
    }

    @isTest
    static void CodingRoundReviewControllerTestMethod() {
        Test.startTest();
            Contact candidate = [SELECT Id from Contact limit 1];
            PageReference testPageRef = Page.CodingQuestionnaire;
        	Test.setCurrentPage(testPageRef);
            ApexPages.currentPage().getParameters().put('key', ExamPortalHelper.encryptKey(candidate.Id)[1]);
        	CodingRoundReviewController codeReviewPage = new CodingRoundReviewController();
        
        	PageReference testPageRef1 = Page.CodingQuestionnaire;
        	Test.setCurrentPage(testPageRef1);
            ApexPages.currentPage().getParameters().put('key', ExamPortalHelper.encryptKey(candidate.Id + '#' + 'testString')[1]);
        	CodingRoundReviewController codeReviewPage1 = new CodingRoundReviewController();
        Test.stopTest();
       
    }
}