force-app/main/default/objects/Contact/fields/Exam_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Exam_Start_Date__c</fullName>
    <label>Exam Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <label>Username</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Written_Test_Status__c.field-meta.xml
<CustomField>
    <fullName>Written_Test_Status__c</fullName>
    <label>Written Test Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Test_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <label>Username</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/globalValueSets/Test_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Not Started</fullName>
    </customValue>
    <customValue>
        <fullName>In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Selected</fullName>
    </customValue>
    <customValue>
        <fullName>On Hold</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <masterLabel>Test Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CandidateLoginHelperTest.cls
/*
Apex Class      :   CandidateLoginHelper, CandidateReportData
*/

@isTest
public class CandidateLoginHelperTest {
    
    @testSetup
    static void candidateData () {
        Map<Object, Object> obj = 
            new Map<Object, Object> {
                'firstName' => 'Kotla',
                    'lastName' => 'Seetha Ramireddy',
                    'dob' => '2002-03-08',
                    'gender' => 'Male',
                    'mobileNumber' => '6303205839',
                    'email' => 'seetharamkotla266@gmailtest.com',
                    'sl' => 'English;Hindi;Telugu;Other',
                    'caddress' => 'APHB Colony, Guntur',
                    'collegeName' => 'Tirumala Engineering College',
                    'gYear' => '2023',
                    'gHallTicketNumber' => '19Ne1a0477',
                    'gPercent' => '65',
                    'interName' => 'Sri Chiatanya Jr College',
                    'interBranch' => 'Other',
                    'interYear' => '2019',
                    'interPercent' => '90',
                    'schoolName' => 'Shivam Merits Public School',
                    'schoolYear' => '2017',
                    'schoolPercent' => '85',
                    'pl' => 'Java;Python;HTML;CSS',
                    'pgName' => 'ANU',
                    'pgBranch' => 'Other',
                    'pgYear' => '2023',
                    'pgHallTicketNumber' => '19ne1a0478',
                    'pgPercent' => '65',
                    'paddress' => 'APHB Colony, Guntur',
                    'otherpgBranch' => 'PG',
                    'otherbranch' => 'Aeronuatical',
                    'otherinterBranch' => 'BiMPC'
                    };
                        CandidateRegistration.registerCandidate(obj);
        
        Contact rejectingCon = new contact();
        rejectingCon.Exam_Start_Date__c = System.today();
        rejectingCon.Written_Test_Status__c = 'Completed';
        rejectingCon.LastName = 'Test1';
        insert rejectingCon;
        
        Account defaultAccount = new Account();
        defaultAccount.Name = System.Label.Default_Account_Name;
        insert defaultAccount;
    }
    
    @isTest
    static void candidateTestMethod() {
        
        Test.startTest();
        
            Lead candidateLead = [SELECT Id, UserName__c FROM Lead LIMIT 1];
        
            CandidateLoginHelper.login('');
            CandidateLoginHelper.login(candidateLead.UserName__c);
            Contact candidate = [SELECT Id, UserName__c FROM Contact WHERE UserName__c = :candidateLead.UserName__c LIMIT 1];
            CandidateLoginHelper.generateQuestions(candidate.Id, 'Java');
            
            CandidateLoginHelper.getCandidateData(candidate.Id);
            CandidateLoginHelper.getCandidateData('');
            
            //CandidateLoginHelper.adminLogin(candidate.UserName__c, System.Label.EP_AdminPassword);
            CandidateReportData.updateStatus(new List<Id> {candidate.Id},
                                             'Written Round Candidate Filter', new List<String>{ 'ramireddy19474@gmail.com'} );
            CandidateLoginHelper.generateQuestions(candidate.Id, 'Java');
            CandidateReportData.updateStatus(new List<Id> {candidate.Id},
                                             'Coding Round Candidate Filter', new List<String>{ 'ramireddy19474@gmail.com'} );
        Test.stopTest();
    }
    
}